//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexanderOnTest.NewNetPageFactory.UnitTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class log4net : global::System.Configuration.ApplicationSettingsBase {
        
        private static log4net defaultInstance = ((log4net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new log4net())));
        
        public static log4net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
